### ISSUE TITLE
K3S compatible?

### ISSUE THREAD

**Issue by jay-a-brown** [Fred78290/kubernetes-vmware-autoscaler#1]
Would this be able to scale K3S https://github.com/rancher/k3s  as well on vmware?

**Comment by Fred78290** [comment]
I don't really know k3s, but after readi g it's look like minikube.

so I think after deployed your master node on a VM hosted on vsphere, and after adding my own version of autoscaler you can probably scale a k3s node. 

You need to write some shell scripts over k3s.
