### ISSUE TITLE
any chance of a 1.17 version of this? maybe some improved examples and docs?

### ISSUE THREAD

**Issue by daveoy** [Fred78290/kubernetes-vmware-autoscaler#2]
or perhaps you coudl lead me in the direction of a how-to-use-this-repo doc / how-to-use-this-container doc?

**Comment by Fred78290** [comment]
Hi, I'm sorry for long delay to reply.
I'm glad to announce that I had ported every thing to latest kubernetes version.
Don't miss also my autoscaler version need to work with this tool.
