### ISSUE TITLE
autoscale pod can't connect to Vmware Vcenter

### ISSUE THREAD

**Issue by redouanebelkasmi** [Fred78290/kubernetes-vmware-autoscaler#22]
Hello,
 I have a problem with the vsphere-autoscaler container which cannot contact the Vcenter Vmware with this error in its logs:
time="2022-02-09T11:17:31Z" level=error msg="can't get the info for VM: xxxxxx, reason: Post \"https:////username:password@vc.test.local\": http: no Host in request URL"

I think it's due to //// but I can't find them in the configmap.

Can you please help me.

Cordially.

**Comment by Fred78290** [comment]
Hello
Take a look

kubectl edit configmap config-cluster-autoscaler -n kube-system
at vmvare.${NODEGROUP_NAME}.url

Delete pod after editing
