### ISSUE TITLE
Autoscale without DHCP server

### ISSUE THREAD

**Issue by redouanebelkasmi** [Fred78290/kubernetes-vmware-autoscaler#23]
Hello,

I successfully deployed the autoscaler in my existing K8S cluster. my question is if i can use the autoscaler to create a new node without a DHCP server in my network and if it is possible HOW?

Cordially.

**Comment by redouanebelkasmi** [comment]
hello, 

I also tested with a dhcp but still without success with the following error:
`level=error msg="Unable to launch VM:vmware-ca-k8s-managed-01 for nodegroup: vmware-ca-k8s. Reason: unable to join the master kubernetes node for VM: vmware-ca-k8s-managed-01, reason: unable to execute command: kubeadm join x.x.x.x:6443 --token xxxxxxxxxxxxxxxxxxxxxxxxx --discovery-token-ca-cert-hash sha256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --apiserver-advertise-address  --ignore-preflight-errors=All, output: , reason:failed to dial: dial tcp :22: connect: connection refused"`
I don't know why the ssh connection does not pass even if I manually tested an ssh connection from the vspher-autoscaler container to the new node created and the connection passes without problem.
I also noticed that in the log only port 22 is mentioned, not the ip of the new VM created.

Cordially

**Comment by Fred78290** [comment]
Hello, which version You use for the vmware-autoscaler ?
Regards

**Comment by redouanebelkasmi** [comment]
Hello,

Latest v1.23.8

Regards.

**Comment by Fred78290** [comment]
- Could you display the CRD used to create the managed VM ?
- Did you also use two network interface ?

Regards

**Comment by Fred78290** [comment]
Are you sure that the created VM is on the same VLAN and the network card is the same as vlan1?

**Comment by Fred78290** [comment]
What is the value of timeout in the vsphere config

**Comment by redouanebelkasmi** [comment]
this is my ssh test 

![image](https://user-images.githubusercontent.com/69789842/186673575-32160ec9-50df-456e-8e24-59b7f9ca8f40.png)

`data:
  grpc-config.json: |
    {
      "address": "unix:/var/run/cluster-autoscaler/vmware.sock",
      "secret": "vmware",
      "timeout": 300,
      "config": {
        "kubeAdmAddress": "x.x.x.x:6443",
        "kubeAdmToken": "xxxxxxxxxxxxxxxxxx",
        "kubeAdmCACert": "sha256:xxxxxxxxxxxxxxxxxxxxxxx",
        "kubeAdmExtraArguments": [
          "--ignore-preflight-errors=All"
        ]
      }
    }`
...
`      "ssh-infos": {
        "user": "root",
        "ssh-private-key": "/root/.ssh/id_rsa"
      },
      "vmware": {
        "vmware-ca-k8s": {
          "url": "https://user:pass@y.y.y.y",
          "uid": "user",
          "password": "pass",
          "insecure": true,
          "dc": "dc01",
          "datastore": "vsanDatastore01",
          "resource-pool": "/dc01/host/cl1/Resources",
          "vmFolder": "/dc01/vm/Infrastructure/K8S/k8s-autoscale",
          "timeout": 300,
          "template-name": "focal-kubernetes-cni-calico-v1.23.3-containerd-amd64",`
Regards.

**Comment by redouanebelkasmi** [comment]
I noticed that during my ssh test it asks me for confirmation of the authenticity of the host and I have to type yes for it to pass. it's normal ?

Regards

**Comment by redouanebelkasmi** [comment]
OS = Ubuntu 20

**Comment by Fred78290** [comment]
> I noticed that during my ssh test it asks me for confirmation of the authenticity of the host and I have to type yes for it to pass. it's normal ?
> 
> Regards

It's normal but in the code the option to ignore keyhost is passed.

So i see that you have try 2 times to ssh in 10.150.1.155 from the host xxx-kgppz, the first one was also connection refused

**Comment by redouanebelkasmi** [comment]
Yes exactly, I think the ssh service goes up after the acqusition of the ip and that explains the first connection refused and when the ssh service goes up the ssh connection passes

Regards.

**Comment by Fred78290** [comment]
Yes the ssh server take more time to start, what is the ESXI type (cpu speed...)
So I must implement a retry for this case

**Comment by redouanebelkasmi** [comment]
still have a problem, 

`time="2022-08-25T14:43:36Z" level=info msg="create managed node vmware-ca-k8s-managed-01 in group: vmware-ca-k8s, node name: vmware-ca-k8s-managed-01"
I0825 14:43:36.654396       1 event.go:294] "Event occurred" object="vmware-ca-k8s-managed-01" kind="ManagedNode" apiVersion="nodemanager.aldunelabs.com/v1alpha1" type="Normal" reason="Success" message="Node vmware-ca-k8s-managed-01 in creation"
time="2022-08-25T14:43:36Z" level=info msg="Launch VM:vmware-ca-k8s-managed-01 for nodegroup: vmware-ca-k8s"
time="2022-08-25T14:47:01Z" level=error msg="Unable to launch VM:vmware-ca-k8s-managed-01 for nodegroup: vmware-ca-k8s. Reason: unable to join the master kubernetes node for VM: vmware-ca-k8s-managed-01, reason: unable to execute command: kubeadm join x.x.x.156:6443 --token yyyyyyyyyyyyy --discovery-token-ca-cert-hash sha256:hhhhhhhhhhhhhhhhhhhhhhhhhhhhhh --apiserver-advertise-address  --ignore-preflight-errors=All, output: , reason:failed to dial: dial tcp :22: connect: connection refused"
time="2022-08-25T14:47:01Z" level=error msg="unable to launch the VM owned by node: vmware-ca-k8s-managed-01, reason: unable to join the master kubernetes node for VM: vmware-ca-k8s-managed-01, reason: unable to execute command: kubeadm join x.x.x.156:6443 --token yyyyyyyyyyyyy --discovery-token-ca-cert-hash sha256:hhhhhhhhhhhhhhhhhhhhhhhhhhhhhh --apiserver-advertise-address  --ignore-preflight-errors=All, output: , reason:failed to dial: dial tcp :22: connect: connection refused"
time="2022-08-25T14:47:07Z" level=info msg="Deleted VM:vmware-ca-k8s-managed-01"
time="2022-08-25T14:47:07Z" level=info msg="Launched node group vmware-ca-k8s of 1 VM failed"
time="2022-08-25T14:47:07Z" level=error msg="could not create all nodes, unable to launch group: vmware-ca-k8s, fail to launch some VMs"
I0825 14:47:07.342168       1 event.go:294] "Event occurred" object="vmware-ca-k8s-managed-01" kind="ManagedNode" apiVersion="nodemanager.aldunelabs.com/v1alpha1" type="Warning" reason="Failed" message="Node vmware-ca-k8s-managed-01 creation failed"`

I don't know why the vm is deleted after two retries ?

Regards.

**Comment by Fred78290** [comment]
I have rebuild the same image with more verbose log, could you try again (pullPolicy = Always)

**Comment by redouanebelkasmi** [comment]
`time="2022-08-25T15:27:22Z" level=info msg="create managed node vmware-ca-k8s-managed-01 in group: vmware-ca-k8s, node name: vmware-ca-k8s-managed-01"`
`I0825 15:27:22.071704       1 event.go:294] "Event occurred" object="vmware-ca-k8s-managed-01" kind="ManagedNode" apiVersion="nodemanager.aldunelabs.com/v1alpha1" type="Normal" reason="Success" message="Node vmware-ca-k8s-managed-01 in creation"`
`time="2022-08-25T15:27:22Z" level=info msg="Launch VM:vmware-ca-k8s-managed-01 for nodegroup: vmware-ca-k8s"`
`time="2022-08-25T15:30:22Z" level=info msg="SSH to host: "`
`time="2022-08-25T15:30:22Z" level=info msg="Connection refused to host: , retry:0"`
`time="2022-08-25T15:30:23Z" level=info msg="Connection refused to host: , retry:1"`
`time="2022-08-25T15:30:24Z" level=info msg="Connection refused to host: , retry:2"`
`time="2022-08-25T15:30:25Z" level=info msg="Connection refused to host: , retry:3"`
`time="2022-08-25T15:30:26Z" level=info msg="Connection refused to host: , retry:4"`
`time="2022-08-25T15:30:27Z" level=info msg="Connection refused to host: , retry:5"`
`time="2022-08-25T15:30:28Z" level=info msg="Connection refused to host: , retry:6"`
`time="2022-08-25T15:30:29Z" level=info msg="Connection refused to host: , retry:7"`
`time="2022-08-25T15:30:30Z" level=info msg="Connection refused to host: , retry:8"`
`time="2022-08-25T15:30:31Z" level=info msg="Connection refused to host: , retry:9"`
`time="2022-08-25T15:30:32Z" level=error msg="Unable to launch VM:vmware-ca-k8s-managed-01 for nodegroup: vmware-ca-k8s. Reason: unable to join the master kubernetes node for VM: vmware-ca-k8s-managed-01, reason: unable to execute command: kubeadm join x.x.x.x:6443 --token xxxxxxxxxxxxxxxxxxxxxxxxxxxx --discovery-token-ca-cert-hash sha256:yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy --apiserver-advertise-address  --ignore-preflight-errors=All, output: , reason:failed to dial: dial tcp :22: connect: connection refused"`
`time="2022-08-25T15:30:32Z" level=error msg="unable to launch the VM owned by node: vmware-ca-k8s-managed-01, reason: unable to join the master kubernetes node for VM: vmware-ca-k8s-managed-01, reason: unable to execute command: kubeadm join x.x.x.x:6443 --token xxxxxxxxxxxxxxxxxxxxxxxxxxxx --discovery-token-ca-cert-hash sha256:yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy --apiserver-advertise-address  --ignore-preflight-errors=All, output: , reason:failed to dial: dial tcp :22: connect: connection refused"`
`time="2022-08-25T15:30:38Z" level=info msg="Deleted VM:vmware-ca-k8s-managed-01"`
`time="2022-08-25T15:30:38Z" level=info msg="Launched node group vmware-ca-k8s of 1 VM failed"`
`time="2022-08-25T15:30:38Z" level=error msg="could not create all nodes, unable to launch group: vmware-ca-k8s, fail to launch some VMs"`
I0825 15:30:38.627889       1 event.go:294] "Event occurred" object="vmware-ca-k8s-managed-01" kind="ManagedNode" apiVersion="nodemanager.aldunelabs.com/v1alpha1" type="Warning" reason="Failed" message="Node vmware-ca-k8s-managed-01 creation failed"

At the same time
![image](https://user-images.githubusercontent.com/69789842/186712247-6eddd4a4-0047-4a63-9468-5c5d4b1843c8.png)


I noticed in the new lines of log 
`time="2022-08-25T15:30:26Z" level=info msg="Connection refused to host: , retry:4"` to host: without ip. is it normal?
Regards

**Comment by Fred78290** [comment]
Haha It means that your ACL used does not allow to retrieve network information because the VM ip is is empty.

You can check it with govc vm info

**Comment by redouanebelkasmi** [comment]
Hello,
I tested retrieving the ip of the vm with govc and it works

![image](https://user-images.githubusercontent.com/69789842/186916106-153ec73d-104b-4e1f-af7e-e1c7b7434d94.png)

I don't know when you build the vm object with all this info (ip, cpu, ...) and if you build it with the data from the crd or you interrogate the vsphere vcenter ?
Regards.

**Comment by Fred78290** [comment]
Well !?!

Could try it starting a new cluster from scratch. I think that the missing DHCP server at your start bring a bug in the state somewhere.
Also must be sure that the VMWare tools is installed inside the template.
