### ISSUE TITLE
Is there a way to specify default host?

### ISSUE THREAD

**Issue by alexnaris** [Fred78290/kubernetes-vmware-autoscaler#6]
here is the error:

2021-08-17 19:49:10.030262 I | Cloud provider:vmware:vmware-ca-k8s call NodeGroup::IncreaseSize got error: code:"cloudProviderError" reason:"could not start VM: vmware-ca-k8s-vm-02, reason: default host resolves to multiple instances, please specify"
W0817 19:49:10.030399       1 clusterstate.go:277] Disabling scale-up for node group vmware-ca-k8s until 2021-08-17 19:58:39.770504247 +0000 UTC m=+1065.506283222; errorClass=Other; errorCode=cloudProviderError
E0817 19:49:10.030504       1 static_autoscaler.go:427] Failed to scale up: failed to increase node group size: could not start VM: vmware-ca-k8s-vm-02, reason: default host resolves to multiple instances, please specifycould not start VM: vmware-ca-k8s-vm-02, reason: default host resolves to multiple instances, please specify

Setting "GOVC_HOST" option in create-masterkube.sh does not help

**Comment by alexnaris** [comment]
looks like this is due to host.autostart.info requiring a host specified..

for now commented out the following  code in server/node.go

      } else if err = vsphere.SetAutoStart(vm.NodeName, -1); err != nil {
              err = fmt.Errorf(constantes.ErrStartVMFailed, vm.NodeName, err)

but is there a better way to get over this?

**Comment by Fred78290** [comment]
Hello, I will look the problem when i will be backdoor from my vacancy.

regards

**Comment by Fred78290** [comment]
Hello, I created a branch named "fix-autostart" based on 1.21 containing a fix for this issue but I have not the ability to test with multiple esxi hosts attached to vsphere.

Could you test it in your vsphere environment and tell me if it's work ?

To test it you need to build your custom image but after reading your comment, I think that's not a problem for you.

The fix is simply to get the running esxi host and use it as autostart host info.

Regards

**Comment by alexnaris** [comment]
So far the fix is working well. 


For your info, your fix even appears to have fixed a bug my work-around introduced as was getting the following error once in a while

`time="2021-08-23T12:43:40Z" level=error msg="Unable to launch VM:vmware-ca-k8s-vm-01 for nodegroup: vmware-ca-k8s. Reason: set labels on node: vmware-ca-k8s-vm-01 got error: Operation cannot be fulfilled on nodes \"vmware-ca-k8s-vm-01\": the object has been modified; please apply your changes to the latest version and try again"`
`time="2021-08-23T12:43:40Z" level=error msg="unable to launch the VM owned by node: vmware-ca-k8s-vm-01, reason: set labels on node: vmware-ca-k8s-vm-01 got error: Operation cannot be fulfilled on nodes \"vmware-ca-k8s-vm-01\": the object has been modified; please apply your changes to the latest version and try again"`

I will more testing today and get back to you shortly.  Thank you

**Comment by alexnaris** [comment]
I can also confirm that auto-start settings did get applied correctly 

```
VM                                           StartAction  StartDelay  StartOrder  StopAction     StopDelay  WaitForHeartbeat
/esxi/vm/k8s-as-test/vmware-ca-k8s-vm-03  powerOn      -1          -1          systemDefault  -1         systemDefault
```

**Comment by Fred78290** [comment]
I will merge the fix around the 12 sept on master
